### ISSUE TITLE
Problems with model inheritance

### ISSUE THREAD

**Issue by ghost** [Brobin/django-seed#27]
django-seed seems to ignore the fields in the base model when I try to seed them. It seeds the fields on the inherited model correctly but when it tries to save the model it throws an error because the fields on the base model are not filled. 

I'll take a look at this later and see if I can fix this.

It might be useful to add Proxy models to the tests as well.

**Comment by LaurensBER** [comment]
It seems to go wrong on _ptr fields which should be treated as the foreign key to the parent model. I can see that model._meta.fields returns this field and that django-seed creates a formatter for this: 'device_ptr': <function ModelSeeder.build_relation.<locals>.func at 0x7f1646ea8d08>.

It inserted the base models and this works without any problems:

{<class 'apps.devices.models.Device'>: [21, 22, 23, 24, 25]}

But I see an error when it starts inserting the inherited models:

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/laurens/Env/seismic-data-hub/lib/python3.4/site-packages/django_seed/seeder.py", line 136, in execute
    entity = self.entities[klass].execute(using, inserted_entities)
  File "/home/laurens/Env/seismic-data-hub/lib/python3.4/site-packages/django_seed/seeder.py", line 74, in execute
    setattr(obj, field, format(inserted_entities))
AttributeError: can't set attribute
```

I'm not sure what the issue is here or why it can't set an attribute.

I'm using Django-Polymorphic on this project and it throws a different error (django_seed.exceptions.SeederException: Field devices.Device.polymorphic_ctype cannot be null) but this can be solved with:

```python
{
    'polymorphic_ctype':    lambda x: ContentType.objects.get(model='Device'),
}
```

Apart from that my models are of the basic:

```python
class Device(PolymorphicModel):
    model = models.CharField(max_length=200, null=True)

class TestDevice(Device):
    description = models.CharField(max_length=200)
```
