### ISSUE TITLE
How do I run the seeder from model instances?

### ISSUE THREAD

**Issue by florestankorp** [Brobin/django-seed#78]
I made a file called `seed.py` in the root of my Django project (next to manage.py) so I can use `Seed.seeder()` . 
When I run the command like this:

`$ python seed.py`

I get the following error:

`django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

**Comment by florestankorp** [comment]
I simply put the `Seeder.seed()` code in `tests.py` and the ran `python manage.py test` from the command line

**Comment by AngelOnFira** [comment]
Ya, you'll need to put the script somewhere where Django calls it instead of you. I'd also recommend looking into [writing your own Django command](https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/) to decouple the seeding from tests, unless you're specifically using it with tests.
